#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BindingLibTestApp.Resource", IsApplication=true)]

namespace BindingLibTestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int showcaseViewStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int sv_backgroundColor = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int sv_buttonBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int sv_buttonForegroundColor = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int sv_buttonText = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int sv_detailTextAppearance = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int sv_detailTextColor = 2130771970;
			
			// aapt resource value: 0x7f010009
			public const int sv_showcaseColor = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int sv_tintButtonColor = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int sv_titleTextAppearance = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int sv_titleTextColor = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int action_bar_offset = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int button_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int showcase_radius = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int showcase_radius_inner = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int showcase_radius_outer = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int text_padding = 2131099653;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_cling_normal = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_cling_pressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cling = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cling_bleached = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cling_button_bg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int hand = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int monoandroidsplash = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int myButton = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int showcase_button = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int showcase_sub_text = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int showcase_title_text = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int handy = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int showcase_button = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ok = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ShowcaseButton = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ShowcaseView = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ShowcaseView_Light = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int TextAppearance_ShowcaseView_Detail = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int TextAppearance_ShowcaseView_Detail_Light = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int TextAppearance_ShowcaseView_Title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int TextAppearance_ShowcaseView_Title_Light = 2131034119;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomTheme = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int CustomTheme_showcaseViewStyle = 0;
			
			public static int[] ShowcaseView = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int ShowcaseView_sv_backgroundColor = 0;
			
			// aapt resource value: 3
			public const int ShowcaseView_sv_buttonBackgroundColor = 3;
			
			// aapt resource value: 4
			public const int ShowcaseView_sv_buttonForegroundColor = 4;
			
			// aapt resource value: 5
			public const int ShowcaseView_sv_buttonText = 5;
			
			// aapt resource value: 6
			public const int ShowcaseView_sv_detailTextAppearance = 6;
			
			// aapt resource value: 1
			public const int ShowcaseView_sv_detailTextColor = 1;
			
			// aapt resource value: 8
			public const int ShowcaseView_sv_showcaseColor = 8;
			
			// aapt resource value: 9
			public const int ShowcaseView_sv_tintButtonColor = 9;
			
			// aapt resource value: 7
			public const int ShowcaseView_sv_titleTextAppearance = 7;
			
			// aapt resource value: 2
			public const int ShowcaseView_sv_titleTextColor = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
